# sudo docker-compose up -d
# sudo docker-compose build
# sudo docker-compose down
# sudo docker-compose ps -a

version: '2'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    ports:
      - "8080:8080"
