# cp -pr stijanic ~/tmp
# cd ~/tmp/stijanic
# sudo docker-compose up -d
# sudo docker-compose build
# sudo docker-compose down
# sudo docker-compose ps -a
# sudo heroku login
# sudo heroku container:push web -a stijanic-docker
# sudo heroku container:release web -a stijanic-docker
# sudo heroku logs --tail -a stijanic-docker

version: '2'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    ports:
      - "8080:8080"
