include $(GNUSTEP_MAKEFILES)/common.make

APP_NAME = HelloWorld Sample Composite Encapsulation
HelloWorld_OBJC_FILES = HelloWorld.m
Sample_OBJC_FILES = Sample.m
Composite_OBJC_FILES = Composite.m
Encapsulation_OBJC_FILES = Encapsulation.m

include $(GNUSTEP_MAKEFILES)/application.make
